version: 2
registries:
  npm-registry-npm-pkg-github-com-navikt-data-catalog-components:
    type: npm-registry
    url: https://npm.pkg.github.com/@navikt/data-catalog-components
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_NAVIKT_DATA_CATALOG_COMPONENTS_TOKEN}}"
  npm-registry-npm-pkg-github-com-deetly-plotly-view:
    type: npm-registry
    url: https://npm.pkg.github.com/@deetly/plotly-view
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_DEETLY_PLOTLY_VIEW_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.39
    - 14.14.41
    - 15.0.0
    - 15.0.1
  - dependency-name: "@craco/craco"
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: nav-frontend-popover
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: nav-frontend-hjelpetekst
    versions:
    - 2.1.2
  - dependency-name: react-intl
    versions:
    - 5.10.19
    - 5.11.0
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
    - 5.13.0
    - 5.13.1
    - 5.13.2
    - 5.16.0
    - 5.17.0
    - 5.17.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
    - 17.0.4
  - dependency-name: "@formatjs/intl-pluralrules"
    versions:
    - 4.0.12
    - 4.0.13
    - 4.0.15
    - 4.0.16
    - 4.0.6
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.10.2
    - 3.11.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.12.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.3
    - 13.1.5
  - dependency-name: "@navikt/sif-common-core"
    versions:
    - 8.0.4
    - 8.1.1
    - 8.3.1
    - 8.4.1
    - 8.4.10
    - 8.4.3
    - 8.4.6
    - 8.4.7
    - 8.5.0
    - 9.0.2
    - 9.1.0
  - dependency-name: nav-frontend-knapper
    versions:
    - 2.1.1
    - 2.1.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: react-modal
    versions:
    - 3.13.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: nav-frontend-lenker
    versions:
    - 1.1.1
  - dependency-name: nav-frontend-paneler
    versions:
    - 2.1.1
  - dependency-name: nav-frontend-core
    versions:
    - 5.1.1
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: i18n-iso-countries
    versions:
    - 6.6.0
    - 6.7.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: nav-frontend-skjema
    versions:
    - 3.0.45
    - 3.1.0
  - dependency-name: dayjs
    versions:
    - 1.10.4
  - dependency-name: nav-frontend-alertstriper
    versions:
    - 3.0.43
  registries:
  - npm-registry-npm-pkg-github-com-navikt-data-catalog-components
  - npm-registry-npm-pkg-github-com-deetly-plotly-view
